name: CI
on: [push]

jobs:
  lint:
    name: Type-check & lint
    runs-on: ubuntu-latest
    steps:
      - name: Install dependencies
        run: npm install
      - name: Type-check all files
        run: npm run type-check
      - name: Run eslint + prettier on staged files
        run: lint-staged
