name: Test typescript-action
on: [push]

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Type-check all files
        run: npm run type-check
      - name: Run eslint + prettier on staged files
        run: lint-staged
