name: CI
on: [push]

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Install dependencies
        run: npm install
      - name: Run type-checking on TS/JS files
        run: npm run type-check
      - name: Run eslint on TS/JS files
        run: npm run lint
      - name: Run prettier on all files
        run: npm run format

  lighthouse:
    name: Lighthouse CI
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Audit URLs using Lighthouse
        uses: treosh/lighthouse-ci-action@v2
        env:
          PR_NUMBER: ${{ github.event.pull_request.number }}
        with:
          urls: |
            https://deploy-preview-$PR_NUMBER--gatsbytutorials.netlify.com
          temporaryPublicStorage: true
