name: CI
on: [push]

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Install dependencies
        run: npm install
      - name: Type-check all files
        run: npm run type-check
      - name: Run eslint + prettier on staged files
        run: npm run validate
